// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orbital.Infrastructure.Persistence;

#nullable disable

namespace Orbital.Infrastructure.Migrations
{
    [DbContext(typeof(OrbitalDbContext))]
    [Migration("20260406120000_OnboardingAndApiKeys")]
    partial class OnboardingAndApiKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");
            // Target model intentionally omitted — snapshot file is authoritative.
#pragma warning restore 612, 618
        }
    }
}
