// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orbital.Infrastructure.Persistence;

#nullable disable

namespace Orbital.Infrastructure.Migrations
{
    [DbContext(typeof(OrbitalDbContext))]
    [Migration("20260406210000_AddSkipStaleSites")]
    partial class AddSkipStaleSites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Orbital.Domain.Navigation.NavigationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationSiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RingId", "OccurredAt");

                    b.ToTable("NavigationEvents", (string)null);
                });

            modelBuilder.Entity("Orbital.Domain.Rings.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Dimension");

                    b.Property<Guid>("FromSiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Label");

                    b.Property<Guid>("RingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToSiteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RingId", "FromSiteId");

                    b.ToTable("Edges", (string)null);
                });

            modelBuilder.Entity("Orbital.Domain.Rings.Ring", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApiOnboardingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublicDirectoryEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublicJoinEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Rings", (string)null);
                });

            modelBuilder.Entity("Orbital.Domain.Rings.RingApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix");

                    b.HasIndex("RingId");

                    b.ToTable("RingApiKeys", (string)null);
                });

            modelBuilder.Entity("Orbital.Domain.Rings.RingMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicantName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RingId");

                    b.ToTable("RingMemberships", (string)null);
                });

            modelBuilder.Entity("Orbital.Domain.Sites.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("Orbital.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Orbital.Domain.Rings.Edge", b =>
                {
                    b.HasOne("Orbital.Domain.Rings.Ring", null)
                        .WithMany("Edges")
                        .HasForeignKey("RingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbital.Domain.Rings.RingApiKey", b =>
                {
                    b.HasOne("Orbital.Domain.Rings.Ring", null)
                        .WithMany("ApiKeys")
                        .HasForeignKey("RingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbital.Domain.Rings.RingMembership", b =>
                {
                    b.HasOne("Orbital.Domain.Rings.Ring", null)
                        .WithMany("Memberships")
                        .HasForeignKey("RingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbital.Domain.Sites.Site", b =>
                {
                    b.OwnsOne("Orbital.Domain.Sites.SiteUrl", "Url", b1 =>
                        {
                            b1.Property<Guid>("SiteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("TEXT")
                                .HasColumnName("Url");

                            b1.HasKey("SiteId");

                            b1.ToTable("Sites");

                            b1.WithOwner()
                                .HasForeignKey("SiteId");
                        });

                    b.OwnsOne("Orbital.Domain.Sites.VerificationToken", "VerificationToken", b1 =>
                        {
                            b1.Property<Guid>("SiteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("VerificationToken");

                            b1.HasKey("SiteId");

                            b1.ToTable("Sites");

                            b1.WithOwner()
                                .HasForeignKey("SiteId");
                        });

                    b.Navigation("Url")
                        .IsRequired();

                    b.Navigation("VerificationToken")
                        .IsRequired();
                });

            modelBuilder.Entity("Orbital.Domain.Users.User", b =>
                {
                    b.OwnsOne("Orbital.Domain.Users.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Orbital.Domain.Users.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();
                });

            modelBuilder.Entity("Orbital.Domain.Rings.Ring", b =>
                {
                    b.OwnsOne("Orbital.Domain.Rings.RingActivityConfig", "ActivityConfig", b1 =>
                        {
                            b1.Property<Guid>("RingId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ActivityConfig_IsEnabled")
                                .HasDefaultValue(false);

                            b1.Property<bool>("CrawlingEnabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ActivityConfig_CrawlingEnabled")
                                .HasDefaultValue(false);

                            b1.Property<decimal>("RecentPostWeight")
                                .HasColumnType("TEXT")
                                .HasColumnName("ActivityConfig_RecentPostWeight")
                                .HasDefaultValue(2.0m);

                            b1.Property<decimal>("RecentUpdateWeight")
                                .HasColumnType("TEXT")
                                .HasColumnName("ActivityConfig_RecentUpdateWeight")
                                .HasDefaultValue(1.5m);

                            b1.Property<int>("ActivityWindowDays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ActivityConfig_ActivityWindowDays")
                                .HasDefaultValue(30);

                            b1.Property<string>("CrawlFrequency")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ActivityConfig_CrawlFrequency")
                                .HasDefaultValue("Daily");

                            b1.Property<bool>("SkipStaleSites")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ActivityConfig_SkipStaleSites")
                                .HasDefaultValue(false);

                            b1.Property<int>("StaleSiteThresholdDays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ActivityConfig_StaleSiteThresholdDays")
                                .HasDefaultValue(90);

                            b1.HasKey("RingId");

                            b1.ToTable("Rings");

                            b1.WithOwner()
                                .HasForeignKey("RingId");
                        });

                    b.Navigation("ActivityConfig")
                        .IsRequired();

                    b.Navigation("ApiKeys");

                    b.Navigation("Edges");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
